### Diferencias np matrix np ndarray

In [1]:
import numpy as np

#### Numpy Matrix 
Retorna una matriz desde un arreglo o un string. Una matriz es un arreglo de dos dimensiones. Contiene algunos operadores especiales como * para multiplicar y ** para potencias. Esta clase se utiliza mucho para algebra lineal

In [2]:
a = np.matrix('1 1; 2 2')
print (a)

[[1 1]
 [2 2]]


#### Numpy Ndarray
Es un arreglo multidimensioneal, en el cual se establece un tamaño y un tipo de datos definido homogeneous array of fixed-size items. An associated data-type object describes the format of each element in the array (its byte-order, how many bytes it occupies in memory, whether it is an integer, a floating point number, or something else, etc.)

In [3]:
a = np.ndarray((2,), buffer=np.array([1,2,3,4,5]),offset=9,dtype=int) 
b = np.ndarray((2,), buffer=np.array([1,2,3,4,5]),dtype=int) 
c = np.ndarray((2,2), buffer=np.array([.1,.2,.3,.4,.5]),dtype=float, order='F') # ordena por columnas
d = np.ndarray((2,2), buffer=np.array([.1,.2,.3,.4,.5]),dtype=float, order='C') # ordena por filas
print(a)
print(b)
print(c)
print(d)

[216172782113783808 288230376151711744]
[1 2]
[[0.1 0.3]
 [0.2 0.4]]
[[0.1 0.2]
 [0.3 0.4]]


#### Diferencias

| Matrix     | Ndarray    |
| ---------- | ---------- |
| 2 Dimensiones   | Multidimensional   |
|Parámetro data obligatorio   | Parámetro Buffer opcional  |
|No ordena   | Permite ordenar por filas y columnas  |

### Referencias

* numpy.ndarray, 
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html
* numpy.matrix, https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html
